const fs = require('fs');

/* This file is used to 'auto' generate the AST node classes for
   statements and expressions. Those nodes all follow a tmeplate,
   so this file defines the attributes required in each node type
   and running it will re-generate all of the class files. */

var statement_types = [
    {
        name: 'Block',
        fields: [
            { name:'statements', type:'Statement[]' },
            { name:'blockAutoGeneratedByCompiler', type:'Boolean' },
            { name:'blockFirstTokenIndex', type:'Number' },
            { name:'blockLastTokenIndex', type:'Number' },
        ]
    },
    {
        name: 'Break',
        fields: [
            { name:'keywordTokenIndex', type:'Number' },
        ]
    },
    {
        name: 'Class',
        fields: [
            { name:'className', type:'Token' },
            { name:'superclassName', type:'Token', optional:true },
            { name:'functions', type:'FunctionStatement[]' }
        ],
        imports: ['Token', 'FunctionStatement']
    },
    {
        name: 'Continue',
        fields: [
            { name:'keywordTokenIndex', type:'Number' },
        ]
    },
    {
        name: 'Debugger',
        fields: [
            { name:'keywordTokenIndex', type:'Number' },
        ]
    },
    {
        name: 'Expression',
        fields: [
            { name:'expression', type:'Expression' },
            { name:'expressionFirstTokenIndex', type:'Number' },
            { name:'expressionLastTokenIndex', type:'Number' },
        ],
        imports: ['Expression']
    },
    {
        name: 'Function',
        fields: [
            { name:'name', type:'Token' },
            { name:'parameters', type:'Token[]' },
            { name:'functionBody', type:'BlockStatement' }
        ],
        imports: ['Token', 'BlockStatement']
    },
    {
        name: 'If',
        fields: [
            { name:'expression', type:'Expression' },
            { name:'thenStatement', type:'Statement' },
            { name:'elseStatement', type:'Statement', optional: true },
            { name:'expressionFirstTokenIndex', type:'Number' },
            { name:'expressionLastTokenIndex', type:'Number' },
            { name:'thenStatementFirstTokenIndex', type:'Number' },
            { name:'thenStatementLastTokenIndex', type:'Number' },
            { name:'elseStatementFirstTokenIndex', type:'Number', optional: true },
            { name:'elseStatementLastTokenIndex', type:'Number', optional: true },
        ],
        imports: ['Expression']
    },
    {
        name: 'Print',
        fields: [
            { name:'expression', type:'Expression' },
            { name:'keywordTokenIndex', type:'Number' },
        ],
        imports: ['Expression']
    },
    {
        name: 'Return',
        fields: [
            { name:'expression', type:'Expression', optional: true },
            { name:'keywordTokenIndex', type:'Number' },
            { name:'expressionFirstTokenIndex', type:'Number', optional: true },
            { name:'expressionLastTokenIndex', type:'Number', optional: true },
        ],
        imports: ['Expression']
    },
    {
        name: 'Throw',
        fields: [
            { name:'expression', type:'Expression' },
            { name:'keywordTokenIndex', type:'Number' },
            { name:'expressionFirstTokenIndex', type:'Number', optional: true },
            { name:'expressionLastTokenIndex', type:'Number', optional: true },
        ],
        imports: ['Expression']
    },
    {
        name: 'Try',
        fields: [
            { name:'tryBody', type:'BlockStatement' },
            { name:'exceptionVariableName', type:'Token', optional: true },
            { name:'catchBody', type:'BlockStatement', optional: true },
            { name:'finallyBody', type:'BlockStatement', optional: true }
        ],
        imports: ['Token', 'BlockStatement']
    },
    {
        name: 'Var',
        fields: [
            { name:'name', type:'Token' },
            { name:'initializerExpression', type:'Expression', optional:true },
            { name:'firstTokenIndex', type:'Number'},
            { name:'lastTokenIndex', type:'Number'}
        ],
        imports: ['Token', 'Expression']
    },
    {
        name: 'While',
        fields: [
            { name:'whileCondition', type:'Expression' },
            { name:'executeStatement', type:'Statement' },
            { name:'keywordTokenIndex', type:'Number' },
            { name:'expressionFirstTokenIndex', type:'Number', optional: true },
            { name:'expressionLastTokenIndex', type:'Number', optional: true },
            { name:'statementFirstTokenIndex', type:'Number', optional: true },
            { name:'statementLastTokenIndex', type:'Number', optional: true },

        ],
        imports: ['Expression']
    },

];

var expression_types = [
    {
        name: 'Assign',
        fields: [
            { name:'name', type:'Token' },
            { name:'value', type:'Expression' }
        ],
        imports: ['Token']
    },
    {
        name: 'Binary',
        fields: [
            { name:'left', type:'Expression' },
            { name:'op', type:'Token' },
            { name:'right', type:'Expression' }
        ],
        imports: ['Token']
    },
    {
        name: 'Call',
        fields: [
            { name:'callee', type:'Expression' },
            { name:'args', type:'Expression[]' },
            { name:'useObjectRef', type:'Boolean' }
        ]
    },
    {
        name: 'Function',
        fields: [
            { name:'parameters', type:'Token[]' },
            { name:'functionBody', type:'BlockStatement' }
        ],
        imports: ['Token', 'BlockStatement']
    },
    {
        name: 'Get',
        fields: [
            { name:'targetObject', type:'Expression' },
            { name:'attributeName', type:'Token' }
        ],
        imports: ['Token']
    },
    {
        name: 'Grouping',
        fields: [
            { name:'expression', type:'Expression' }
        ]
    },
    {
        name: 'IndexerGet',
        fields: [
            { name:'targetObject', type:'Expression' },
            { name:'indexerExpression', type:'Expression' }
        ]
    },
    {
        name: 'IndexerSet',
        fields: [
            { name:'targetObject', type:'Expression' },
            { name:'indexerExpression', type:'Expression' },
            { name:'valueExpression', type:'Expression' }
        ]
    },
    {
        name: 'Literal',
        fields: [
            { name:'value', type:'Object' }
        ]
    },
    {
        name: 'Logical',
        fields: [
            { name:'left', type:'Expression' },
            { name:'op', type:'Token' },
            { name:'right', type:'Expression' }
        ],
        imports: ['Token']
    },
    {
        name: 'NewInstance',
        fields: [
            { name:'className', type:'Token' },
            { name:'ctorArgs', type:'Expression[]' }
        ],
        imports: ['Token']
    },
    {
        name: 'ObjectInitializer',
        fields: [
            { name:'name', type:'Token' },
            { name:'value', type:'Expression' }
        ],
        imports: ['Token']
    },
    {
        name: 'Set',
        fields: [
            { name:'targetObject', type:'Expression' },
            { name:'attributeName', type:'Token' },
            { name:'valueExpression', type:'Expression' }
        ],
        imports: ['Token']
    },
    {
        name: 'Ternary',
        fields: [
            { name:'evaluationExpression', type:'Expression' },
            { name:'expresisonIfTrue', type:'Expression' },
            { name:'expresisonIfFalse', type:'Expression' }
        ]
    },
    {
        name: 'Unary',
        fields: [
            { name:'op', type:'Token' },
            { name:'right', type:'Expression' }
        ],
        imports: ['Token']
    },
    {
        name: 'Variable',
        fields: [
            { name:'name', type:'Token' },
            { name:'unaryOperator', type:'TokenType', optional:true }
        ],
        imports: ['Token', 'TokenType']
    }
];

// Create statement files

var stmt_import_strings = {
    'Expression':  'import org.smolscript.internals.ast.expressions.Expression;\n',
    'Token': 'import org.smolscript.internals.Token;\n'
}

var expr_import_strings = {
    'Statement':  'import org.smolscript.internals.ast.statements.Statement;\n',
    'Token': 'import org.smolscript.internals.Token;\n',
    'TokenType': 'import org.smolscript.internals.TokenType;\n'
}

statement_types.forEach(function(st) {
    console.log(st.name);

    var imports = '';
    var fields = '';
    var ctorParams = '';
    var ctorAssigns = '';

    if (st.imports != null) {
        st.imports.forEach(function(imp) {
            if (stmt_import_strings[imp] != null) {
                imports += stmt_import_strings[imp];
            }
            else if (imp.endsWith('Statement')) {
                imports += `import org.smolscript.internals.ast.statements.${imp};\n`;
            }
            else if (imp.endsWith('Expression')) {
                imports += `import org.smolscript.internals.ast.expressions.${imp};\n`;
            }
            else {
                throw new Error(`Can't handle importing ${imp}`);
            }

        });
    }

    st.fields.forEach(function(f) {
        ctorParams += `${ctorParams.length > 0 ? ', ':''}${f.type} ${f.name}`
        fields += `    public final ${f.type} ${f.name};\n`;
        ctorAssigns += `${ctorAssigns.length > 0 ? '\n':''}        this.${f.name} = ${f.name};`;
    })

    var classDefn = `package org.smolscript.internals.ast.statements;

${imports}

public class ${st.name}Statement extends Statement {

${fields}

    public ${st.name}Statement(${ctorParams}) {
${ctorAssigns}
    }

    public Object accept(IStatementVisitor visitor) {
        return visitor.visit(this);
    }
}`

    fs.writeFileSync(`./src/main/java/org/smolscript/internals/ast/statements/${st.name}Statement.java`, classDefn);
});


expression_types.forEach(function(ex) {
    console.log(ex.name);

    var imports = '';
    var fields = '';
    var ctorParams = '';
    var ctorAssigns = '';

    if (ex.imports != null) {
        ex.imports.forEach(function(imp) {
            if (expr_import_strings[imp] != null) {
                imports += expr_import_strings[imp];
            }
            else if (imp.endsWith('Statement')) {
                imports += `import org.smolscript.internals.ast.statements.${imp};\n`;
            }
            else if (imp.endsWith('Expression')) {
                imports += `import org.smolscript.internals.ast.expressions.${imp};\n`;
            }
            else {
                throw new Error(`Can't handle importing ${imp}`);
            }
        });
    }

    ex.fields.forEach(function(f) {
        fields += `    public final ${f.type} ${f.name};\n`;
        ctorParams += `${ctorParams.length > 0 ? ', ':''}${f.type} ${f.name}`
        ctorAssigns += `${ctorAssigns.length > 0 ? '\n':''}        this.${f.name} = ${f.name};`;
    })

    var classDefn = `package org.smolscript.internals.ast.expressions;

${imports}

public class ${ex.name}Expression extends Expression {

${fields}

    public ${ex.name}Expression(${ctorParams}) {
${ctorAssigns}
    }

    public Object accept(IExpressionVisitor visitor) {
        return visitor.visit(this);
    }
}`

    fs.writeFileSync(`./src/main/java/org/smolscript/internals/ast/expressions/${ex.name}Expression.java`, classDefn);

});
