package org.smolscript.internals.ast.statements;



public class BlockStatement extends Statement {

    public final Statement[] statements;
    public final Boolean blockAutoGeneratedByCompiler;
    public final Number blockFirstTokenIndex;
    public final Number blockLastTokenIndex;


    public BlockStatement(Statement[] statements, Boolean blockAutoGeneratedByCompiler, Number blockFirstTokenIndex, Number blockLastTokenIndex) {
        this.statements = statements;
        this.blockAutoGeneratedByCompiler = blockAutoGeneratedByCompiler;
        this.blockFirstTokenIndex = blockFirstTokenIndex;
        this.blockLastTokenIndex = blockLastTokenIndex;
    }

    public Object accept(IStatementVisitor visitor) {
        return visitor.visit(this);
    }
}